---
title: "Tools"
---

The following tools are used within the Hop community.

* <<github, Github>>
* <<jira, Jira>>
* <<wiki, Wiki>>
* <<forum, Forum>>
* <<chat, Mattermost Chat>>

== anchor:github[]GitHub
All our source code is publicly available on GitHub, GitHub is a Git repository hosting service, but it adds many of its own features. While Git is a command line tool, GitHub provides a Web-based graphical interface. It also provides access control and several collaboration features.

Our repositories can be found https://github.com/project-hop[here , window="_blank"]

While GitHub provides solutions to do issue tracking we use a separate platform for this.

== anchor:jira[]Jira

All new features and issues found in Hop can be reported in our bug tracker. If you find an issue or want to request new features first read our link:/community/contribution-guides/jira-guide/[Jira-guide] this document contains the basic steps needed to create a ticket that we can work on.

To see what we are currently working on visit our https://project-hop.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=HOP[Jira Board , window="_blank"]

== anchor:wiki[]Wiki

All documentation is written in Wiki style documents and resides in it's own repository or close to the code, this means all our documentation is version controlled and we have an easy and fast system to accept contributions from the community. More information on documentation contribution and guidelines can be found link:/community/contribution-guides/documentation-contribution-guide/[here].

== anchor:forum[]Forum

For user with questions we created a stack overflow like question board. It allows everyone to ask a question and a voting and acceptance system for the answers. The forum can be found https://forums.project-hop.org[here , window="_blank"].

== anchor:chat[]Mattermost Chat

Mattermost is a chat client that is comparable to Slack it is an opensource alternative that allows us to invite everyone to come join us and chat with the developers or ask question, feel free to join and start https://chat.project-hop.org[chatting , window="_blank"].